services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: goomer
      POSTGRES_PASSWORD: goomer
      POSTGRES_DB: goomer_api
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
